services:
  pgsqldb:
    image: ghcr.io/curt/postgis:latest
    build: ./postgis
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - type: volume
        source: pgsqldata
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    ports:
      - "8089:5432"
  app:
    image: ghcr.io/curt/kamino:latest
    build: .
    restart: unless-stopped
    env_file:
      - .env
    links:
      - pgsqldb
    ports:
      - "8088:8080"
  admin:
    image: ghcr.io/curt/kamino-admin:latest
    build: .
    restart: unless-stopped
    env_file:
      - .env
    links:
      - app
    ports:
      - "8087:8080"

volumes:
  pgsqldata:
